$(".folderLevel").click(e=>{		
	$.ajax({
		url:contextPath+"/diary/diaryFolder",
		type:"post",
		data:{
			"folderNo":$(e.target).parent().next().val(),
			"loginMemberId":$("input[name='loginMemberId']").val(),
			"hostMemberId":$("input[name='hostMemberId']").val(),
			"shareLevel":$(e.target).parent().next().next().val()				
		},
		dataType:"html",
		success:data=>{				
			$("#right-page").html(data);
		}
	});				
});

$("#diary_folder_setting_btn").click(e=>{
	$.ajax({
		url:contextPath+"/diary/FolderSetting",
		type:"post",
		data:{
			"loginMemberId":$("input[name='loginMemberId']").val(),
			"hostMemberId":$("input[name='hostMemberId']").val()
		},
		dataType:"html",
		success:data=>{				
			$("#right-page").html(data);
		}
	})
});