document.getElementById("jukeboxMenu").addEventListener("click",(e)=>{
    console.log("테스트테스트");
    $.ajax({
        url:contextPath+"/page/minihomeRightPageToJukebox.do",
        type:"post",
        dataType:"html",
        data:{"album":e.target.innerText,"hostMemberId":hostMemberId},
        success:(data)=>{
            $("#right-page").html(data);
        }
    });
});

document.getElementById("addAlbum").addEventListener("click",(e)=>{
    $.ajax({
        url:contextPath+"/page/minihomeLeftPageToJukebox.do",
        type:"post",
        dataType:"html",
        data:{"hostMemberId":hostMemberId,"newAlbumTitle":$("#newAlbumTitle").val()},
        success:(data)=>{
            $("#left-page").html(data);
        }
    });
});

document.getElementById("deleteAlbum").addEventListener("click",(e)=>{
    console.log($("#albumForDelete").val());
    $.ajax({
        url:contextPath+"/page/minihomeLeftPageToJukebox.do",
        type:"post",
        dataType:"html",
        data:{"hostMemberId":hostMemberId,"albumForDelete":$("#albumForDelete").val()},
        success:(data)=>{
            $("#left-page").html(data);
        }
    });
});