document.getElementById("jukeboxMenu").addEventListener("click",(e)=>{
    $.ajax({
        url:contextPath+"/page/minihomeRightPageToJukebox.do",
        type:"post",
        data:{"album":e.target.innerText.substring(0,e.target.innerText.indexOf("[")),"hostMemberId":hostMemberId},
        dataType:"html",
        success:(data)=>{
            $("#right-page").html(data);
        }
    });
    $.ajax({
        url:contextPath+"/page/minihomeLeftPageToJukebox.do",
        type:"post",
        data:{"hostMemberId":hostMemberId,"currentFolder":$(e.target).text().substring(0,$(e.target).text().indexOf("["))},
        dataType:"html",
        success:(data)=>{
            $("#left-page").html(data);
        }
    });
});

document.getElementById("addAlbum").addEventListener("click",(e)=>{
    $.ajax({
        url:contextPath+"/page/minihomeLeftPageToJukebox.do",
        type:"post",
        dataType:"html",
        data:{"hostMemberId":hostMemberId,"newAlbumTitle":$("#newAlbumTitle").val()},
        success:(data)=>{
            $("#left-page").html(data);
        }
    });
});

document.getElementById("deleteAlbum").addEventListener("click",(e)=>{
    $.ajax({
        url:contextPath+"/page/minihomeLeftPageToJukebox.do",
        type:"post",
        dataType:"html",
        data:{"hostMemberId":hostMemberId,"albumForDelete":$("#albumForDelete").val()},
        success:(data)=>{
            $("#left-page").html(data);
        }
    });
});