$("#diaryFolderSaveBtn").click(e=>{	
	$.ajax({
		url:contextPath+"/diary/folderWrite",
		type:"post",
		data:{
			"folderShareLevel":$("#folderShareLevel").val(),
			"addFolderName":$("#addFolderName").val(),
			"hostMemberId":$("input[name='hostMemberId']").val(),
			"loginMemberId":$("input[name='loginMemberId']").val()
		},
		dataType:"html",
		success:data=>{
			$("#left-page").html(data);
		}		
	});		
});

$("#diaryMemberBtn").click(e=>{
	$.ajax({
		url:contextPath+"/diary/addFriend",
		type:"post",
		data:{
			"shareMember":$("#shareMember").val(),
			"shareFolderNo":$("#shareFolderNo").val(),
			"folderName":$(e.target).innerText(),
			"hostMemberId":$("input[name='hostMemberId']").val(),
			"loginMemberId":$("input[name='loginMemberId']").val()
		},
		dataType:"html",
		success:data=>{
			console.log(folderName);
			$("#left-page").html(data);
		}		
	});	
});


$("#diary_del_folder_btn").click(e=>{
	$.ajax({
		url:contextPath+"/diary/folderDelete",
		type:"post",
		data:{			
			"delFolderNo":$("#folderName").val()
		},
		dataType:"html",
		success:data=>{
			$("#left-page").html(data);
		}		
	})
});